project_name := "pangea"
build: setup
    cargo build --release --target=wasm32-unknown-unknown
    cp ./target/wasm32-unknown-unknown/release/{{project_name}}.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm pangea_engine.wick
debug: setup
    cargo +nightly build --target=wasm32-wasi
    cp ./target/wasm32-wasi/debug/{{project_name}}.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm pangea_engine.wick
setup:
    mkdir -p build
test: build
    wick test pangea_engine.wick
clean:
  cargo clean
